### ISSUE TITLE
Shortcut fusion

### ISSUE THREAD

**Issue by winterbe** [winterbe/streamjs#45]
Performance could be improved for some stream chains by applying an optimization strategy called shortcut fusion. E.g. this `.filter(a).filter(b)`could be replaced by `.filter(a && b)`.

See: https://wiki.haskell.org/Short_cut_fusion

**Comment by erosb** [comment]
Hi!

I think it doesn't really make sense to put effort into it. Such shortcut fusion IMO makes sense only if it can be performed on the AST level, in other words, during some kind of compilation or source-level optimization. The best you can do in javascript (in runtime, ie. when the second `filter()` call occurs) is probably:
* creating a new function which wraps both the `a()` and `b()` call
* and put it into a single `filter()` call

It doesn't really make sense for me. You reduce the number of the `filter()` calls by introducing a new function calling both `a` and `b` filters. Very little gain, if at all.

You cannot traverse/dig into the body of the `a` and `b` filtering functions therefore you cannot inline-compile (transform) them, as you could at compile-time in a compiled language.

If I were you, I'd close this issue. Better let the JIT do such micro-optimizations (since the JIT is able to perform inline-compilation, if it finds it necessary).

**Comment by winterbe** [comment]
Hi,

thanks for your input on that. I guess you right, it's barely more than a micro optimization since we cannot inline functions calls in JavaScript. However the streaming pipeline adds a notable overhead in form of additional function calls compared to the naive imperative approach. 

E.g. if you split up complex filtering into multiple filter predicates, each filter function results in additional function calls internally (`advance` and `pipe`): https://github.com/winterbe/streamjs/blob/master/stream.js#L211-L228

These additional function calls could simply be eliminated by implementing something like `CombinedFilterOp`, which accepts multiple function predicates and performs all filtering ad once.

However this projects currently lacks serious performance tests, so we cannot proof any real performance benefits when using this optimization on a large input collection.
