### ISSUE TITLE
Filter stopped working

### ISSUE THREAD

**Issue by jeppec** [winterbe/streamjs#50]
Hi

We've had a filter for  a long time and suddenly it stopped working.

This code used to work:
$scope.data.lastQuotes = Stream($scope.data.lastQuotes).filter({quoteId: !quoteId}).toArray();

I had to change it to this to make it work:

$scope.data.lastQuotes = Stream($scope.data.lastQuotes).filter(function (quote) { return quote.quoteId !== quoteId;}).toArray();

Note quoteId is a string and lastQuotes is an array of objects - contains something along these line (as JSON):
[
  {
    "quoteId": "test-quote-2",
    "state": "Draft",
    "name": "test-reference-2",
  },
  {
    "quoteId": "test-quote-1",
    "state": "Draft",
    "name": "test-reference-1",
  }
]

We've been running version 1.6.4 all the time - so I'm not sure what actually caused filter to break - any ideas?

/Jeppe

**Comment by erosb** [comment]
`$scope.data.lastQuotes = Stream($scope.data.lastQuotes).filter({quoteId: !quoteId}).toArray();`

I'm afraid it was totally broken, just took some time to cause actual problems. This code negates a truthy/falsy value of `quoteId` to boolean and negates it, therefore that filter will select the elements which' `quoteId` property is `true` or `false` (depending on the original value of `quoteId`).

On the other hand the second version filters the elements which' `quoteId` property is not the same as the `quoteId` value. That is something totally different, and I guess the latter is the expected behavior

**Comment by jeppec** [comment]
I definitely see your point - I was so focused on why it stopped working that it missed my eyes ;)
I think the way it was built was copied from an example - but I'm not sure.

Weird part is that it worked for quite a while AND none of the QuoteId's were ever a boolean - guess it just shows the wonders of Javascript :-?

**Comment by winterbe** [comment]
Thanks @erosb for clarifying. 

Please also see docs for [filter by sample](https://github.com/winterbe/streamjs/blob/master/APIDOC.md#filtersample) for further explanation of underlying semantics.
