### ISSUE TITLE
Skip Nulls Mode

### ISSUE THREAD

**Issue by winterbe** [winterbe/streamjs#6]
Special `skipNulls` intermediate operation switches the whole pipeline into a mode where nulls and undefined is skipped. Nulls could be present in input collection or returned by mapping functions. This should also respect non-existing paths (see #1 and #4 and #2).

**Comment by erosb** [comment]
Not a bad idea, but I think it would be better to add some standard predicates for such filterings instead of adding new intermediate filtering operators. I mean - at the API level - something like:
```javascript
Stream(people)
  .filter(Stream.nonNull) // filters nulls but keeps undefined, 0, Nan, etc (non-null but falsy values)
  .filter(Stream.truthy)  // skips any falsy values
 // ....
```

So I think it would result in a cleaner API do add these standard predicates (`Stream.nonNull` and `Stream.truthy`) instead of adding new intermediate operators.

The names can be different if you want. I'm not sure about `truthy`, but I'd really prefer `nonNull`, since this streamjs library is originally the port of the Java8 stream API, and in Java streams I like using the `java.util.Objects#nonNull(obj)` method for the same purpose. `Stream.nonNull(obj)` would be a decent port for it.

I can implement it today if you clarify it.

**Comment by winterbe** [comment]
I agree with you that a special `mode` is not the right way to handle nulls. However I'm afraid that your solutions pollutes the `Stream` namespace. Also it's not clear when reading `Stream.nonNull` that this function returns a predicate and not a stream.

Adding a separate namespace inside Stream would solve this problem:

```js
Stream(people)
  .filter(Stream.Predicates.nonNull)
```

However for my taste it's ugly and too much text to type.


After thinking about this I would prefer to just add special filtering functions like Kotlin does in it's std lib: http://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/kotlin.-array/filter-not-null.html

```js
Stream(people)
  .filterNotNull()
```

I'm not entirely sure what variants we need: `filterNotNull`, `filterNotUndefined` and `filterExists` (= not null and not undefined)? Not sure about the latter.

**Comment by erosb** [comment]
> filterNotNull, filterNotUndefined and filterExists

Maybe it is better to stick to the terminology being widely used in the javascript world, ie. `filterNull` (removing only for `null` values) and `filterFalsy` (removing every [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) values: `null` , `undefined`, `""`, 0, `false`, `NaN`)

**Comment by winterbe** [comment]
Your proposal makes perfectly sense. :+1: 

Thanks for the falsy link. Didn't know it's kind of an official term. We should put this link into the APIDOC for 'filterFalsy'.
